name: reusable workflow   

on:
  workflow_call:
    inputs:
      json-file:
        required: true
        type: string

jobs:
  pepe:
    runs-on: ubuntu-latest

    steps:
      - name: Take values of config
        run: |
          key = $(jq -r 'keys[]' ${{inputs.json-file}})
          echo "VALUE= $(jq -r ".$key ${{inputs.json-file}}")"
