name: reusable workflow   

on: workflow_dispatch
  # workflow_call:
  #   inputs:
  #     json-file:
  #       required: true
  #       type: string

jobs:
  json-job:
    runs-on: ubuntu-latest

    steps:
      - name: Take values of config
        run: |
          echo ${{inputs.json-file}}

