name: Github Actions Matrix

on:
  push:
    branches:
      - main
jobs:
  read_config:
    runs-on: ubuntu-latest

    outputs:
      lambda: ${{steps.get-lambdas-name.outputs.matrix}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get configs var
        id: get-lambdas-name
        run: |
          JSON=$(cat ./config.json)
          echo $JSON
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  deploy:
    needs: [read_config]

    strategy:
      matrix: ${{fromJson(needs.read_config.outputs.lambda)}}

    uses: ./.github/workflows/reusable2.yml
    with:
      json-file: "${{matrix}}"
