name: Github Actions Matrix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Reading config.json
        run: |
         echo "LAMBDA_NAME=$(jq -r '.lambda_name' ./config.json)" >> $GITHUB_ENV
         echo "LAMBDA_NAME=$(jq -r '.bucket_name' ./config.json)" >> $GITHUB_ENV
         echo "LAMBDA_NAME=$(jq -r '.path" ./config.json)' >> $GITHUB_ENV
         echo "LAMBDA_NAME=$(jq -r '.artifact_name' ./config.json)" >> $GITHUB_ENV
  